name: Bug Report
description: File a bug report
title: "File a bug report"
body:
  - type: markdown
    attributes:
      value: |
        To help us processing your bug report, please fill out this form!
  - type: checkboxes
    id: options
    attributes:
      label: Can you reproduce the bug in vscode.dev or in VS Code Desktop?
      description: Can you reproduce the bug in [vscode.dev](https://vscode.dev) or in VS Code Desktop?
      options:
        - label: Not reproducible on [vscode.dev](https://vscode.dev) or VS Code Desktop
          required: true
  - type: checkboxes
    id: options2
    attributes:
      label: Can you reproduce the bug in the monaco editor playground?
      description: Can you reproduce the bug in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)?
      options:
        - label: Not reproducible on [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)
  - type: textarea
    id: what-happened
    attributes:
      label: Monaco Editor Playground Code
      description: Please provide the code to reproduce in the monaco editor playground
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe the actual behavior, as observed in the playground
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the expected behavior

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Context
      description: Please provide additional context
